---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  namespace: url-shortener
spec:
  encryptedData:
    POSTGRES_DB: AgATlQNXqFtpQsvcuUGNkYL8h4NQ7dQe1MKZtEAv8KZqtGFMSFEOetl1tKnlawTd/VpcQiu4Norah3fe5SNW5LvFVcbAqxRcdmzKLYcOxVFtMltYvWb1/lnDEEEeAlQ33M1NuaQ2EVKAUWWlpPpdPjGs64gtRKbvaiXSl5lz+hyYlYjBL0F+LUBNPXYGEf4lHLG4S61pIhnWMXQ5mbXbzOECrIh4tdDLYZU+/H6WO9wffaLKnQhBvx/SReYDMBKfMPDS8L8NpvYRi+XLwukjZyujxpKSrXvMGNcyLhGw+0U+u/BoIDUZqfYYY3jGGUQN1D6cElil0Xr1DqM3QD+MCeFht32CrOluMSAitTyA9YDToJMlRTC9TXYudmV4jv77kiDvQKHdq2tPKerEkEluv98DahUEFavhWYJTMF1kuQxQUmpPPXC0KoblmSpRDKU+Q0VqLlUvkbrwsX8bi1NfK7vOuT9J0B+C1nx1rHf6zZMGrZu3qdEPVsvANJjWTbYJaaKkureUjGWMsXgHTdsvrEn2j97r2Ld3A9+6M/Hx6UzhHQOoYqrzAeviTTi3M9Zo3v3ciK7qEzlCPIK/V2oPx88DMaLJeMTTXTuTqA38McxiQ8hxC9FWK3cP357FM6TYHTsNs0d2eeIPwYKoLnEZH0S1PCZdfZIHjtTZHqw4WylKEqvBUg9HpQvNsovz26N9/XHL/ulNJIda7AS+4HY=
    POSTGRES_PASSWORD: AgCsXGVzt/fLq9MoQggyD5emYLaudGRymI1VQKoahRpUEF2DBFuFR3mrSkrtkSssG3rgY7IW2++6UbwRlP/UM9jPspguoFUpwhDSPezYGU4dbGtoxCafcZLyAMxIHyRhMdkInyFQv5uiqegWvjencubN6ts1+j/rTasVE+y3wRv0H3a24lOytCzG/hXLwWJUdyV8kWZzAxLxtGsufd4eJBzdoxGEqJ5miOFrdO0NkbyD9uBHaQiFG3ql+cmXkFEgtXOIO7Xv82pOUvJYqfcgUGOUWyaZvoRVXf17CYQB6LO4o2Lg8/rntFVSEjHxkZ/GjQcbNxf7OGUcG7CYq7JgtXSiQEE/bABEqoLArp5Q8E6iBzfNnv2g3m/vRcT4qTbGDjepqUv/AtT5XiDYXm8a5JcUqhR4lDHKBSA99QVpJ9bs0INIyIeCjW6cNigFbNY5bczuax0mMAxFkTNfwycHTY76zufA/uz94J04QplSRex0ayOyFzgIM/+uHyz1CRjgW2ONX2iak4HYD3Pnw+UfKr0R1cn7WEx7Daqx6BU9sWhleYmf8twnu0Mqh5pPhYmeEgrgCr6vTybOYZ3tT9LAQXD8MEoT3I1GyU/Z2qAEcoCB2706CAv3+VV/W+Pu3U+YxHv0R6eBDGEh/8Rwe4JpAHt5+CbcghNV3COnBX8tlr8614775JSF5Ggkf8NGIqwy3285c820CVRwCg==
  template:
    metadata:
      name: postgres-secret
      namespace: url-shortener
    type: Opaque
