---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  namespace: url-shortener
spec:
  encryptedData:
    POSTGRES_DB: AgBrDos/+LHsnt0pypnxKjrrzVOZc5Bm3O4oj8qlUOpan4jB8SYS8EjsWL2U20CjBa94Y1vz8UAPfG03+TMYUUcBRtDUtolBxrh5Qxj28ZE6AQQrVDvf/SNjLdbxiAiOwkJxiGDuKSGHo6iv99Kb4cZEfcVTdt6fh8d1PsNVeYDC5lG5we+VM9OFfZPBZBmA3HLCJb/73ASrAllfsJpqB2lwiXhIyF1LSEfJpuI9JZNkHtIIk7G7SLgVaqnf7P7mx8GLXMwV2snFir3mTMA429MLPyZ22ee9qH4grMYyeDf/A8r/DN+5IYEeTGaIuD3f+H2Y+9xyZ15MoSqqC1yNvY2l6F9Zl++gVnVq+Vk5fZVA3NFY8dH9NgieUXqD3TtrpT9rZgV1VHhwBNX6FRnusYtKPx8c5nBxMstkNhECuyROdiE3hGnh0fsWN5Z2fonhYmZAmog1t4oga7Gmtm4cWRFdlr+JpjzscdJ4hmgJbSR3zUDB+cNhzoX11Tp+lMV2VVrHPzeh9qLB1rdG8MvCP6HVve13KsLnQpwXRWFWtB0J/YHear7MvkCUo9CT+DtexsHWHkrdaOq2OWBZb/cFFzlpoDxUU7bHX633Uhm/+GMISKfZ9TcDEvkyrW+9JiJQTdn/BzFFKgVQXMpg59KYTUXSHp4IvsAXUjPwVBxLi+6KzUag91jYL4H+srrVUih+289Ro9MH7aj/RrpExgQ=
    POSTGRES_PASSWORD: AgA924a+NqRoFx+8hFXOfNTLEpPQVaZLbtHZb3S3FKVFoF2HkLXKOwAVd4BlWlECdjxEYrSJnqZuERT6+dYX31Fv0kiBRtjsS7zCLZv+KWM8TXIrXwF4QdG4hK0LQZjitVftOSAU4sPKhe3wCWd/65ujISUDErA8/xHLibUjNMJc7ZNbVHAppqerFx3L6wfwQbtGeh2wEFxasGOll35pGNjnnwSoqEHRRYFCjmabYxnls554Udd2VMz+BMkxieB0Lus6PjdwaTFHUn6TbT1H5Xur2+5ZtYoKKUnGh3qidO2vGOao68H5tvcXtvIeUgdDVrTIWlQ2O2b8O+MHo6ltv00bL5jlrrWIwiXrQaJRL3ceve/BmRVFcfU5RQYoMQxtY5Rf4w6YzDu2l/3tEtQP3fO+Bn5IWwPTWHAHlPCylm2KKY2M+rwLlenb4ph60q/cMeCKdCpRIK1wSjEH28D2kkPU4Z1g3UKI7ExZdd3DMJhAgzoxw/ksNuiDAxH1mQLCGRegb74q7v+2S3Hv668UaRVQn6rGfE7gTawoZFhww7yrZQTrdh/dE8zv+zgWRFrCjWAZeObXI88lIijuLijsO1/6TW20jVWc1m/38u0/FKnTWEgg42jVHbHQNmgSGcnwyCp59s1/ViBqSeEx18ndiE27+hhVbti7r8wEjeTWDV6jfuTYx4XFROou6UCeqluhtF037CpTGqI84w==
  template:
    metadata:
      name: postgres-secret
      namespace: url-shortener
